/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#b2eee7',
        'on-primary-fixed-variant': '#0c4f4a',
        'on-secondary-fixed': '#00201a',
        'primary-fixed-dim': '#96d2cb',
        'primary-container': '#0b4f4a',
        'on-primary-container': '#84bfb8',
        'on-primary-fixed': '#00201d',
        'on-surface-variant': '#3f4947',
        'surface-container-high': '#eae7e7',
        'on-secondary-fixed-variant': '#005144',
        'background': '#fcf9f8',
        'on-surface': '#1b1b1b',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-highest': '#e5e2e1',
        'inverse-on-surface': '#f3f0ef',
        'surface-container': '#f0eded',
        'surface-bright': '#fcf9f8',
        'surface-tint': '#2c6862',
        'inverse-surface': '#313030',
        'outline': '#707977',
        'surface-dim': '#dcd9d9',
        'inverse-primary': '#96d2cb',
        'secondary-container': '#a2f2de',
        'tertiary-container': '#5a4200',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#251a00',
        'tertiary': '#3f2d00',
        'surface-container-low': '#f6f3f2',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#197161',
        'surface': '#fcf9f8',
        'on-background': '#1b1b1b',
        'on-tertiary': '#ffffff',
        'secondary': '#0e6a5b',
        'on-tertiary-container': '#e3ab00',
        'error-container': '#ffdad6',
        'primary': '#003733',
        'secondary-fixed': '#a2f2de',
        'tertiary-fixed-dim': '#f9bd14',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'outline-variant': '#bfc8c6',
        'surface-variant': '#e5e2e1',
        'tertiary-fixed': '#ffdf9d',
        'secondary-fixed-dim': '#86d5c3',
        'on-tertiary-fixed-variant': '#5b4300'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px'
      },
      spacing: {
        'space-xxs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'margin-desktop': '3rem',
        'margin-tablet': '2rem',
        'margin-mobile': '1rem',
        'container-max': '88rem',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'subheading': ['Inter', 'sans-serif'],
        'caption': ['Inter', 'sans-serif'],
        'label-action': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'headline-sm': ['Noto Serif', 'serif'],
        'display-hero': ['Noto Serif', 'serif'],
        'label-bilingual-kannada': ['Noto Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
